#:kivy 1.10.0

<CategoryBox>:
	title: _title
	description: _description
	size_hint_y: None
	height: 50
	Button:
		size_hint_x: .3
		text: '[b][i]Update[/i][/b]'
		markup: True
	BoxLayout:
		size_hint_x: .4
		BoxLayout:
			orientation: 'vertical'
			Label:
				id: _title
				halign: 'left'
				valign: 'middle'
				markup: True
			Label:
				id: _description
				halign: 'left'
				valign: 'middle'
				markup: True
	Button:
		size_hint_x: .3
		text: '[b][i]Remove[/i][/b]'
		markup: True
