#:kivy 1.10.1


<PasswordInput>:
    password_input: _password_input
    confirm_password_input: _confirm_password_input
    orientation: 'vertical'
    TextInput:
        id: _password_input
        hint_text: 'Password'
        multiline: False
        password: True
    TextInput:
        id: _confirm_password_input
        hint_text: 'Confirm Password'
        multiline: False
        password: True
