#:kivy 1.10.1
#: import AppActionBar uix.actionbars.app.AppActionBar


<CategoryScreen>:
	BoxLayout:
		orientation: 'vertical'
		AppActionBar:
			screen_manager: root.manager
		BoxLayout:
			size_hint_y: .8
			# TODO: Add Category List Here
		BoxLayout:
			orientation: 'vertical'
			size_hint_y: .2
			Button:
				text: '[b]Add New Category'
				markup: True
			Button:
				text: '[b]Back to Main Menu[/b]'
				markup: True
				on_release: root.manager.current = 'main'
