#:kivy 1.10.1
#:import AppActionBar uix.actionbars.app.AppActionBar


<AccountScreen>:
	BoxLayout:
		orientation: 'vertical'
		AppActionBar:
			screen_manager: root.manager
		BoxLayout:
			size_hint_y: .8
		BoxLayout:
			orientation: 'vertical'
			size_hint_y: .2
			Button:
				text: '[b][color=ff0000]Delete Account[/color][/b]'
				markup: True
			Button:
				text: '[b]Back to Main Menu[/b]'
				markup: True
				on_release: root.manager.current = 'main'
